CREATE TABLE "books" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(30) NOT NULL,
  "author_lastname" varchar(50) NOT NULL,
  "review" varchar NOT NULL,
  "rating" integer NOT NULL,
  "date_read" datetime NOT NULL,
  "isbn" varchar NOT NULL
);

CREATE TABLE "chapters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "position_in_book" integer NOT NULL,
  "title" varchar NOT NULL,
  "book_id" integer NOT NULL
);

CREATE TABLE "notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "text" varchar NOT NULL,
  "book_id" integer NOT NULL,
  "chapter_id" integer,
  "created_at" datetime NOT NULL
);

CREATE UNIQUE INDEX "UC_title_position_in_book" ON "chapters" ("book_id", "position_in_book");

CREATE UNIQUE INDEX "UC_title_author" ON "books" ("id", "author_lastname");

CREATE UNIQUE INDEX "UC_book_chapter_title" ON "chapters" ("book_id", "title");

ALTER TABLE "chapters" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") ON DELETE CASCADE;

ALTER TABLE "notes" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") ON DELETE CASCADE;

ALTER TABLE "notes" ADD FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id") ON DELETE CASCADE;
